name: Android CI Releases

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew assembleRelease  # Ensure we build the release variant

    - name: Check APK file existence
      run: |
        echo "Listing APK files in the build folder:"
        ls ./app/build/outputs/apk/release  # List release APK files to debug

    - name: Compress build folder
      run: |
        ZIP_FILE="android-build-$(date +'%Y%m%d%H%M%S').zip"
        echo "Compressing android/app/build directory into $ZIP_FILE"
        zip -r $ZIP_FILE ./app/build  # Compress the build directory
        ls -lh $ZIP_FILE  # List the compressed file

    - name: Create Release
      id: create_release
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"  # Create a unique version tag
        echo "Creating release with tag: $TAG_NAME"
        gh release create $TAG_NAME $ZIP_FILE --title "Release $TAG_NAME" --notes "Automated release with build files"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure GH_TOKEN is set

    - name: Upload Zip to Release
      run: |
        TAG_NAME="v$(date +'%Y%m%d%H%M%S')"
        echo "Uploading $ZIP_FILE to release"
        gh release upload $TAG_NAME $ZIP_FILE --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure GH_TOKEN is set
